# Generated by Django 3.2.3 on 2021-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
