# Generated by Django 3.2.3 on 2021-05-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210520_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='movie',
            new_name='movies',
        ),
    ]
