# Generated by Django 3.2.3 on 2021-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movie_collection_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star_rating_average',
            field=models.FloatField(default=0),
        ),
    ]
