# Generated by Django 3.2.3 on 2021-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
    ]
